# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
